// <auto-generated />
using System;
using EnergyMonitoring.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnergyMonitoring.Migrations
{
    [DbContext(typeof(EnergyContext))]
    [Migration("20260509041916_1_Init")]
    partial class _1_Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnergyMonitoring.Models.Energy15Minute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("EnergyKwh")
                        .HasColumnType("real");

                    b.Property<float>("MaxPower")
                        .HasColumnType("real");

                    b.Property<DateTime>("Minute")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Energy15Minutes");
                });

            modelBuilder.Entity("EnergyMonitoring.Models.EnergyDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Day")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float>("EnergyKwh")
                        .HasColumnType("real");

                    b.Property<float>("MaxPower")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("EnergyDays");
                });

            modelBuilder.Entity("EnergyMonitoring.Models.EnergyHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("EnergyKwh")
                        .HasColumnType("real");

                    b.Property<DateTime>("Hour")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float>("MaxPower")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("EnergyHours");
                });

            modelBuilder.Entity("EnergyMonitoring.Models.EnergyMinute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("EnergyKwh")
                        .HasColumnType("real");

                    b.Property<float>("MaxPower")
                        .HasColumnType("real");

                    b.Property<DateTime>("Minute")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("EnergyMinutes");
                });

            modelBuilder.Entity("EnergyMonitoring.Models.PzemRaw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Alarm")
                        .HasColumnType("integer");

                    b.Property<float>("Current")
                        .HasColumnType("real");

                    b.Property<float>("Energy")
                        .HasColumnType("real");

                    b.Property<float>("Frequency")
                        .HasColumnType("real");

                    b.Property<float>("Power")
                        .HasColumnType("real");

                    b.Property<float>("PowerFactor")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float>("Voltage")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PzemRaws");
                });
#pragma warning restore 612, 618
        }
    }
}
